### ISSUE TITLE
Can't add plugins through admin interface

### ISSUE THREAD

**Issue by cmadland** [OleVik/grav-skeleton-scholar#2]
I've just installed the scholar skeleton (extracted to webserver, Direct Install didn't work) and everything seems to be fine, except I can't add plugins though the admin interface. 

### error page.

<img width="1652" alt="Screen Shot 2020-01-30 at 10 31 14 AM 1" src="https://user-images.githubusercontent.com/12282929/73479124-34c32080-434c-11ea-9413-169e4bd9eb1a.png">

### Plugin list:
<img width="424" alt="Screen Shot 2020-01-30 at 10 37 06 AM" src="https://user-images.githubusercontent.com/12282929/73479331-a1d6b600-434c-11ea-8d85-47b1cf4b25aa.png">

**Comment by OleVik** [comment]
This is an [upstream](https://github.com/getgrav/grav/issues/2782)-issue with Grav's use of the Toolbox-library, which should be fixed when RC.4 is released. When that happens, I'll update the skeleton.

**Comment by cmadland** [comment]
should I roll something back?

**Comment by OleVik** [comment]
At current, the only fix is to roll back to a stable version of Grav Core, say 1.6.19, or to update Core + Admin to latest from source. I'm expecting RC.4 to be released very soon.

**Comment by cmadland** [comment]
Ok...I should be ok for a bit. Thank you.

**Comment by OleVik** [comment]
Fixed upstream.
