### ISSUE TITLE
ReadOnlyStream::stream_set_option is not implemented

### ISSUE THREAD

**Issue by ttben** [OleVik/grav-skeleton-scholar#3]
Hi!

# Issue
I am struggling to (re)use this skeleton, and the issue seems to be in the scholar theme.
When I download the latest release of this skeleton, I got the following error

```
require_once(): \RocketTheme\Toolbox\StreamWrapper\ReadOnlyStream::stream_set_option is not implemented!
```

this line 
`Grav\Theme\Scholar registerShortcodes …/user/themes/scholar/scholar.php:92`

calls this line 
`Grav\Plugin\ShortcodeManager registerAllShortcodes …/user/themes/scholar/scholar.php:466`

which trigger the issue later on.

# Environment
 
The error stack trace confirm that I am running an ok-version of php

```
SERVER_SOFTWARE | "Apache/2.4.41 (Unix) PHP/7.4.2"
SERVER_NAME | "localhost"
SERVER_ADDR | "::1"
SERVER_PORT | "80"
```

# Debug

- A google search lead me [to this](https://github.com/rockettheme/toolbox/issues/28)
I am not sure if this is related to the theme, grav, or my php installation...

- a `./bin/gpm update` yield a `env: php\r: No such file or directory`. It seems that a file has a `crlf` end-of-line that may broke the use of the skeleton.

If you have any clue, I can try things :)
I am happy to see a scholar theme on grav!

**Comment by OleVik** [comment]
This is an issue that has been fixed upstream, but I'll hold off on re-assembling the skeleton until 1.7 of Core is released as stable. There's been many changes between the beta-versions and release-candidates for 1.7, so I'll need to test the whole of it with a stable ecosystem.

**Comment by OleVik** [comment]
I locked the current release-cycle to only target the stable version of Grav; v[1.0.6](https://github.com/OleVik/grav-skeleton-scholar/releases/tag/1.0.6) ships with Grav 1.6.21 and Admin 1.9.12.
